export const iranCities = [
  { en: "Tehran", fa: "تهران" },
  { en: "Mashhad", fa: "مشهد" },
  // { en: "Isfahan", fa: "اصفهان" },
  // { en: "Shiraz", fa: "شیراز" },
  { en: "Tabriz", fa: "تبریز" },
  { en: "Karaj", fa: "کرج" },
  { en: "Qom", fa: "قم" },
  { en: "Ahvaz", fa: "اهواز" },
  { en: "Kermanshah", fa: "کرمانشاه" },
  { en: "Rasht", fa: "رشت" },
  { en: "Zahedan", fa: "زاهدان" },
  { en: "Yazd", fa: "یزد" },
  { en: "Hamedan", fa: "همدان" },
  { en: "Arak", fa: "اراک" },
  { en: "Bandar Abbas", fa: "بندرعباس" },
  { en: "Zanjan", fa: "زنجان" },
  { en: "Sanandaj", fa: "سنندج" },
  { en: "Kerman", fa: "کرمان" },
  { en: "Gorgan", fa: "گرگان" },
  { en: "Sari", fa: "ساری" },
];
